//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int employee_id { get; set; }
        public string dept_name { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
